#Sunny_Wu_wusunny1_1010978239
#Ivan_Zhuo_zhuoiva1_1011039984

reset;

# import .mod and .dat files
model warpshoes.mod;
data warpshoes.dat;

# choose gurobi as the solving tool
option solver gurobi;

# solve the program
solve;

# round the OUTPUT x-values (not the x-values for calculations) to the nearest integer  
# write profit, number of shoes produced, and which warehouses should open to an output file 
display Profit, {i in SHOE_TYPE} (round(x[i])), z > MIE262_project.out;

