#Sunny_Wu_wusunny1_1010978239
#Ivan_Zhuo_zhuoiva1_1011039984

reset;

# import .mod and .dat files
model warpshoes.mod;
data warpshoes.dat;

# choose gurobi as the solving tool
option solve gurobi;

# solve the program
solve;

# write profit, number of shoes produced, and which warehouses to open to an output file 
display Profit, x, z > MIE262_project.out;

# close output file
close MIE262_project.out;
